/**
 * generated by Xtext 2.22.0
 */
package ac.soton.java.barebones.bareBones;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Clear</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ac.soton.java.barebones.bareBones.BareBonesPackage#getClear()
 * @model
 * @generated
 */
public interface Clear extends Statement
{
} // Clear
