/*
 * generated by Xtext 2.22.0
 */
package ac.soton.java.barebones.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractBareBonesValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(ac.soton.java.barebones.bareBones.BareBonesPackage.eINSTANCE);
		return result;
	}
}
