/*
 * generated by Xtext 2.15.0
 */
package ac.soton.java.barebones


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BareBonesStandaloneSetup extends BareBonesStandaloneSetupGenerated {

	def static void doSetup() {
		new BareBonesStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
