/*
 * generated by Xtext 2.15.0
 */
package ac.soton.java.barebones


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BareBonesRuntimeModule extends AbstractBareBonesRuntimeModule {
}
