/**
 * generated by Xtext 2.22.0
 */
package ac.soton.java.barebones.bareBones.impl;

import ac.soton.java.barebones.bareBones.BareBonesPackage;
import ac.soton.java.barebones.bareBones.Decrement;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Decrement</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DecrementImpl extends StatementImpl implements Decrement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DecrementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BareBonesPackage.Literals.DECREMENT;
  }

} //DecrementImpl
