/*
 * generated by Xtext 2.22.0
 */
package ac.soton.java.barebones.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBareBonesScopeProvider extends DelegatingScopeProvider {
}
