/*
 * generated by Xtext 2.22.0
 */
package ac.soton.java.barebones.ide.contentassist.antlr;

import ac.soton.java.barebones.ide.contentassist.antlr.internal.InternalBareBonesParser;
import ac.soton.java.barebones.services.BareBonesGrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class BareBonesParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(BareBonesGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, BareBonesGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
			builder.put(grammarAccess.getClearAccess().getGroup(), "rule__Clear__Group__0");
			builder.put(grammarAccess.getIncrementAccess().getGroup(), "rule__Increment__Group__0");
			builder.put(grammarAccess.getDecrementAccess().getGroup(), "rule__Decrement__Group__0");
			builder.put(grammarAccess.getWhileAccess().getGroup(), "rule__While__Group__0");
			builder.put(grammarAccess.getProgramAccess().getStatementsAssignment(), "rule__Program__StatementsAssignment");
			builder.put(grammarAccess.getClearAccess().getNameAssignment_2(), "rule__Clear__NameAssignment_2");
			builder.put(grammarAccess.getIncrementAccess().getNameAssignment_2(), "rule__Increment__NameAssignment_2");
			builder.put(grammarAccess.getDecrementAccess().getNameAssignment_2(), "rule__Decrement__NameAssignment_2");
			builder.put(grammarAccess.getWhileAccess().getNameAssignment_2(), "rule__While__NameAssignment_2");
			builder.put(grammarAccess.getWhileAccess().getStatementsAssignment_7(), "rule__While__StatementsAssignment_7");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private BareBonesGrammarAccess grammarAccess;

	@Override
	protected InternalBareBonesParser createParser() {
		InternalBareBonesParser result = new InternalBareBonesParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public BareBonesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BareBonesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
