/*
 * generated by Xtext 2.22.0
 */
package ac.soton.java.barebones.ui;

import ac.soton.java.barebones.ui.internal.BarebonesActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BareBonesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(BarebonesActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		BarebonesActivator activator = BarebonesActivator.getInstance();
		return activator != null ? activator.getInjector(BarebonesActivator.AC_SOTON_JAVA_BAREBONES_BAREBONES) : null;
	}

}
