/*
 * generated by Xtext 2.22.0
 */
package ac.soton.java.barebones.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BareBonesAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("ac/soton/java/barebones/parser/antlr/internal/InternalBareBones.tokens");
	}
}
